DROP TABLE IF EXISTS groups;
CREATE TABLE IF NOT EXISTS groups (
   gr_id INTEGER PRIMARY KEY,
   gr_name CHAR(10)
);
DROP TABLE IF EXISTS students;
CREATE TABLE IF NOT EXISTS students (
   st_id INTEGER PRIMARY KEY AUTOINCREMENT,
   st_name VARCHAR(30),
   st_group INTEGER, FOREIGN KEY (st_group) REFERENCES groups (gr_id)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT 
);
DROP TABLE IF EXISTS teachers;
CREATE TABLE IF NOT EXISTS teachers (
   tc_id INTEGER PRIMARY KEY,
   tc_name VARCHAR(30)
);
DROP TABLE IF EXISTS subjects;
CREATE TABLE IF NOT EXISTS subjects (
   sj_id INTEGER PRIMARY KEY AUTOINCREMENT,
   sj_name VARCHAR(25) UNIQUE NOT NULL,
   sj_teach INTEGER, 
   FOREIGN KEY (sj_teach) REFERENCES teachers (tc_id)
      ON DELETE RESTRICT
      ON UPDATE RESTRICT
);
DROP TABLE IF EXISTS assessments;
CREATE TABLE IF NOT EXISTS assessments (
   as_id INTEGER PRIMARY KEY AUTOINCREMENT,
   as_assess TINYINT UNSIGNED NOT NULL,
   as_week TINYINT UNSIGNED NOT NULL,
   as_subj INTEGER, 
   as_stud INTEGER, 
   FOREIGN KEY (as_subj) REFERENCES subjects (sj_id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
   FOREIGN KEY (as_stud) REFERENCES students (st_id)
      ON DELETE CASCADE
      ON UPDATE CASCADE
);